name: Get Changed Folder

on:
  push:
    branches:
      - main

jobs:
  get_changed_folder:
    runs-on: ubuntu-20.04 # Use Ubuntu 20.04 which comes with Node.js 16

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Find changed folder
        id: find_changed_folder
        run: |
          # Use git to get the list of changed files
          if [[ -n "${{ github.event.before }}" ]]; then
            changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          else
            # If github.event.before is not available (e.g., on the first commit of a branch), just get the changed files in the current commit
            changed_files=$(git diff --name-only ${{ github.sha }}^)
          fi


          # Loop through the changed files to find the folders
          for file in $changed_files; do
            # Extract the folder path
            folder=$(dirname "$file")

            # Print the folder name
            echo "::set-output name=changed_folder::$folder"
          done

      - name: Use the changed folder
        run: |
          # Access the changed folder from the previous step's output
          changed_folder="${{ steps.find_changed_folder.outputs.changed_folder }}"
          echo "Changed folder is: $changed_folder"
