name: Update Networks JSON

on:
  push:
    branches:
      - main  # replace with your default branch if it's not 'main'

jobs:
  update-networks-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install jq for JSON manipulation
      run: sudo apt-get install -y jq

    - name: Iterate through directories and update networks.json
      run: |
        # Initialize an empty array to collect JSON objects
        jsonArray="[]"

        # Iterate through directories
        for dir in $(find . -maxdepth 1 -type d); do
          # Skip the '.git' and current '.' directories
          if [[ "$dir" != "./.git" && "$dir" != "." ]]; then
            # Iterate through JSON files in the directory
            for jsonFile in $dir/*.json; do
              # Make sure the glob gets at least one file
              [[ -e "$jsonFile" ]] || continue
              
              # Read JSON and append to the array
              jsonObj=$(cat $jsonFile)
              jsonArray=$(echo $jsonArray | jq --argjson newObj "$jsonObj" '. + [$newObj]')
            done
          fi
        done

        # Update networks.json with the collected array
        echo $jsonArray > networks.json
